refactor: rename `dnp` references to `dna` across the project
- Replaced all instances of `dnp` with `dna` in filenames, environment
  variables, bash scripts, and code for consistency.
- Updated documentation, dotenv files, test configurations, and Docker
  scripts to reflect the new naming convention.
- Adjusted paths, function names, and usage examples to align with the
  `dna` standard.

Issue NMO-713

diff --git a/src/bin/dna b/src/bin/dna
--- a/src/bin/dna
+++ b/src/bin/dna
@@ -1,30 +1,30 @@
 #!/bin/bash
-# bin/dnp
+# bin/dna
 
-DOCUMENTATION_BUFFER_DNP=$( cat <<'EOF'
+DOCUMENTATION_BUFFER_DNA=$( cat <<'EOF'
 # =================================================================================================
-#                                  Dockerized-NorLab-Project (DNP)
+#                            Dockerized-NorLab project application (DNA)
 #                         A tool for managing Docker-based robotic projects
 #
 # Usage:
-#   $ dnp COMMAND [OPTIONS]
+#   $ dna COMMAND [OPTIONS]
 #
 # Commands:
-#   init        Initialize a new DNP project
-#   build       Build DNP Docker images
+#   init        Initialize a new DNA project
+#   build       Build DNA Docker images
 #   up          Start and attach to a container (daemon mode)
 #   down        Stop containers
 #   attach      Attach to a running container
 #   exec        Execute command in a running container
 #   run         Run a command in a container
 #   project     Super project commands
-#   save        Save DNP Docker image to file for offline use
-#   load        Load DNP Docker image from file for offline use
+#   save        Save DNA Docker image to file for offline use
+#   load        Load DNA Docker image from file for offline use
 #   config      (In-progress) Show configuration
-#   version     Show DNP version
+#   version     Show DNA version
 #   help        Show this help message
 #
-# Run 'dnp COMMAND --help' for more information on a command.
+# Run 'dna COMMAND --help' for more information on a command.
 #
 # =================================================================================================
 EOF
@@ -42,20 +42,20 @@ else
   _script_path="$(realpath -q "${BASH_SOURCE[0]:-.}")"
   _target_path="$(dirname "${_script_path}")"
 fi
-dnp_core="$(dirname "${_target_path}")/lib/core"
+dna_core="$(dirname "${_target_path}")/lib/core"
 
 # ::::Load dependencies::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
-source "${dnp_core}/utils/import_dnp_lib.bash" || exit 1
+source "${dna_core}/utils/import_dna_lib.bash" || exit 1
 
 # ::::Pre-condition::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
-dnp_error_prefix="\033[1;31m[DNP error]\033[0m"
-test -n "$( declare -f dnp::import_lib_and_dependencies )" || { echo -e "${dnp_error_prefix} The DNP lib is not loaded!" 1>&2 && exit 1; }
-test -n "$( declare -f n2st::print_msg )" || { echo -e "${dnp_error_prefix} The N2ST lib is not loaded!" 1>&2 && exit 1; }
-test -d "${DNP_ROOT:?err}" || { echo -e "${dnp_error_prefix} library load error!" 1>&2 && exit 1; }
-test -d "${DNP_LIB_PATH:?err}" || { echo -e "${dnp_error_prefix} library load error!" 1>&2 && exit 1; }
+dna_error_prefix="\033[1;31m[DNA error]\033[0m"
+test -n "$( declare -f dna::import_lib_and_dependencies )" || { echo -e "${dna_error_prefix} The DNA lib is not loaded!" 1>&2 && exit 1; }
+test -n "$( declare -f n2st::print_msg )" || { echo -e "${dna_error_prefix} The N2ST lib is not loaded!" 1>&2 && exit 1; }
+test -d "${DNA_ROOT:?err}" || { echo -e "${dna_error_prefix} library load error!" 1>&2 && exit 1; }
+test -d "${DNA_LIB_PATH:?err}" || { echo -e "${dna_error_prefix} library load error!" 1>&2 && exit 1; }
 
 # ::::Command functions::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
-function dnp::entrypoint() {
+function dna::entrypoint() {
 
   # ....Set env variables (pre cli)................................................................
   local the_command="$1"
@@ -63,109 +63,109 @@ function dnp::entrypoint() {
 
   # ....cli........................................................................................
   if [[ -z ${the_command}  ]]; then
-    dnp::show_entrypoint_help "${DOCUMENTATION_BUFFER_DNP:?err}"
+    dna::show_entrypoint_help "${DOCUMENTATION_BUFFER_DNA:?err}"
     exit 0
   fi
 
   case "${the_command}" in
       init)
-          source "${DNP_LIB_PATH}/commands/init.bash" || exit 1
-          dnp::init_command "$@"
+          source "${DNA_LIB_PATH}/commands/init.bash" || exit 1
+          dna::init_command "$@"
           exit $?
           ;;
       build)
-          source "${DNP_LIB_PATH}/commands/build.bash" || exit 1
-          dnp::build_command "$@"
+          source "${DNA_LIB_PATH}/commands/build.bash" || exit 1
+          dna::build_command "$@"
           exit $?
           ;;
       save)
-          source "${DNP_LIB_PATH}/commands/save.bash" || exit 1
-          dnp::save_command "$@"
+          source "${DNA_LIB_PATH}/commands/save.bash" || exit 1
+          dna::save_command "$@"
           exit $?
           ;;
       load)
-          source "${DNP_LIB_PATH}/commands/load.bash" || exit 1
-          dnp::load_command "$@"
+          source "${DNA_LIB_PATH}/commands/load.bash" || exit 1
+          dna::load_command "$@"
           exit $?
           ;;
       exec)
-          source "${DNP_LIB_PATH}/commands/exec.bash" || exit 1
-          dnp::exec_command "$@"
+          source "${DNA_LIB_PATH}/commands/exec.bash" || exit 1
+          dna::exec_command "$@"
           exit $?
           ;;
       attach)
-          source "${DNP_LIB_PATH}/commands/attach.bash" || exit 1
-          dnp::attach_command "$@"
+          source "${DNA_LIB_PATH}/commands/attach.bash" || exit 1
+          dna::attach_command "$@"
           exit $?
           ;;
       up)
-          source "${DNP_LIB_PATH}/commands/up.bash" || exit 1
-          dnp::up_command "$@"
+          source "${DNA_LIB_PATH}/commands/up.bash" || exit 1
+          dna::up_command "$@"
           exit $?
           ;;
       down)
-          source "${DNP_LIB_PATH}/commands/down.bash" || exit 1
-          dnp::down_command "$@"
+          source "${DNA_LIB_PATH}/commands/down.bash" || exit 1
+          dna::down_command "$@"
           exit $?
           ;;
       run)
-          source "${DNP_LIB_PATH}/commands/run.bash" || exit 1
-          dnp::run_command "$@"
+          source "${DNA_LIB_PATH}/commands/run.bash" || exit 1
+          dna::run_command "$@"
           exit $?
           ;;
       config)
-          source "${DNP_LIB_PATH}/commands/config.bash" || exit 1
-          dnp::config_command "$@"
+          source "${DNA_LIB_PATH}/commands/config.bash" || exit 1
+          dna::config_command "$@"
           exit $?
           ;;
       version)
-          source "${DNP_LIB_PATH}/commands/version.bash" || exit 1
-          dnp::version_command "$@"
+          source "${DNA_LIB_PATH}/commands/version.bash" || exit 1
+          dna::version_command "$@"
           exit $?
           ;;
       project)
           sub_the_command="$1"
           shift || true
 
-          source "${DNP_LIB_PATH}/commands/project.bash" || exit 1
+          source "${DNA_LIB_PATH}/commands/project.bash" || exit 1
           if [[ -z ${sub_the_command}  ]]; then
-            dnp::command_help_menu "${DOCUMENTATION_BUFFER_PROJECT:?err}"
+            dna::command_help_menu "${DOCUMENTATION_BUFFER_PROJECT:?err}"
             exit 0
           fi
 
           case "${sub_the_command}" in
               validate)
-                  dnp::project_validate_command "$@"
+                  dna::project_validate_command "$@"
                   exit $?
                   ;;
               sanity)
-                  dnp::project_sanity_command "$@"
+                  dna::project_sanity_command "$@"
                   exit $?
                   ;;
               dotenv)
-                  dnp::project_dotenv_command "$@"
+                  dna::project_dotenv_command "$@"
                   exit $?
                   ;;
               help|--help|-h)
-                  dnp::command_help_menu "${DOCUMENTATION_BUFFER_PROJECT:?err}"
+                  dna::command_help_menu "${DOCUMENTATION_BUFFER_PROJECT:?err}"
                   exit 0
                   ;;
               *)
-                  dnp::unknown_subcommand_msg "project" "${sub_the_command}"
+                  dna::unknown_subcommand_msg "project" "${sub_the_command}"
                   exit 1
                   ;;
           esac
           ;;
       help|--help|-h)
-          dnp::show_entrypoint_help "${DOCUMENTATION_BUFFER_DNP:?err}"
+          dna::show_entrypoint_help "${DOCUMENTATION_BUFFER_DNA:?err}"
           exit 0
           ;;
       *)
-          dnp::unknown_command_msg "${the_command}"
+          dna::unknown_command_msg "${the_command}"
           exit 1
           ;;
   esac
 }
 
 # ::::Main:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
-dnp::entrypoint "$@"
+dna::entrypoint "$@"
