feat: improve script dependency loading, test setup/teardown logic and streamline cli help
- Improve dnp entrypoint show help functions
- Introduce `ui.bash` for console related functions
   - added header and footer related functions
   - added various unknown msg functions
   - added general show help functions
- Replaced redundant dependency checks with centralized `dnp::is_lib_loaded` across multiple scripts for better consistency.
- (tests) Simplified teardown logic by removing explicit teardown functions where handled by trap commands.
- Enhanced error handling and feedback in `load_super_project_config.bash` with `n2st::print_msg_error`.

Issue NMO-656

diff --git a/src/bin/dnp b/src/bin/dnp
--- a/src/bin/dnp
+++ b/src/bin/dnp
@@ -6,6 +6,11 @@ DOCUMENTATION_BUFFER_DNP=$( cat <<'EOF'
 #                                  Dockerized-NorLab-Project (DNP)
 #                         A tool for managing Docker-based robotic projects
 #
+# What it does:
+#   • Provide a dockerized environment for [Local|remote] development, deployment, CI-testings and runing slurm jobs
+#   • Support l4t/arm64 (jetson), darwin/arm64 (Mac OsX) and linux/x86 os and architecture
+#   • Support nvidia GPU through nvidia-docker on both l4t/arm64 and linux/x86
+#
 # Usage:
 #   $ dnp COMMAND [OPTIONS]
 #
@@ -38,8 +43,10 @@ source "${dnp_core}/utils/import_dnp_lib.bash"
 
 function dnp::entrypoint() {
   # ....Pre-condition..............................................................................
-  test -d "${DNP_ROOT:?err}" || { echo "The DNP lib load error!" ; exit 1 ; }
-  test -d "${DNP_LIB_PATH:?err}" || { echo "The DNP lib load error!" ; exit 1 ; }
+  local dnp_error_prefix="\033[1;31m[DNP error]\033[0m"
+  test -d "${DNP_ROOT:?err}" || { echo -e "${dnp_error_prefix} librairy load error!" ; exit 1 ; }
+  test -d "${DNP_LIB_PATH:?err}" || { echo -e "${dnp_error_prefix} librairy load error!" ; exit 1 ; }
+#  n2st::print_msg "test" 2>/dev/null >/dev/null || { echo -e "${dnp_error_prefix} The N2ST lib is not loaded!" ; exit 1 ; }
 
   # ....Set env variables (pre cli)................................................................
   # Parse command
@@ -49,7 +56,6 @@ function dnp::entrypoint() {
   # ....cli........................................................................................
   if [[ -z ${the_command}  ]]; then
     dnp::show_entrypoint_help
-    exit 1
   fi
 
   case "${the_command}" in
@@ -86,6 +92,10 @@ function dnp::entrypoint() {
           shift || true
 
           source "${DNP_LIB_PATH}/commands/project.bash" || exit 1
+          if [[ -z ${sub_the_command}  ]]; then
+            dnp::command_help_menu "${DOCUMENTATION_BUFFER_PROJECT:?err}"
+          fi
+
           case "${sub_the_command}" in
               validate)
                   dnp::project_validate "$@"
@@ -97,51 +107,43 @@ function dnp::entrypoint() {
                   dnp::project_dotenv "$@"
                   ;;
               help|--help|-h)
-                  dnp::project_help
-                  exit 1
+                  dnp::command_help_menu "${DOCUMENTATION_BUFFER_PROJECT:?err}"
                   ;;
               *)
-                  echo "Unknown super subcommand: ${sub_the_command}"
-                  dnp::project_help
-                  exit 1
+                  dnp::unknown_subcommand_msg "project" "${sub_the_command}"
                   ;;
           esac
           ;;
       help|--help|-h)
           dnp::show_entrypoint_help
-          exit 0
           ;;
       *)
-          echo "‼️Unknown command: ${the_command}"
-          echo "Here is the help menu ⬇︎. Hope it provide assistance."
-          dnp::show_entrypoint_help_no_splash
-          exit 1
+          dnp::unknown_command_msg "${the_command}"
           ;;
   esac
 }
 
 function dnp::show_entrypoint_help() {
-    echo -e "${MSG_DIMMED_FORMAT}"
-
     # Splash type: small, negative or big
-    n2st::norlab_splash 'Dockerized-NorLab-Project' 'https://github.com/norlab-ulaval/dockerized-norlab-project.git' 'big'
+    n2st::norlab_splash 'Dockerized-NorLab-Project' 'https://github.com/norlab-ulaval/dockerized-norlab-project.git' 'negative'
     n2st::echo_centering_str 'A tool for managing Docker-based robotic projects' "\033[1;37m" " "
 
-    # Strip shell comment char `#` and both lines
-    echo -e "${DOCUMENTATION_BUFFER_DNP}" | sed 's/\# ====.*//' | sed 's/^\#//' | sed 's/Dockerized-NorLab-Project (DNP)//' | sed 's/A tool for managing Docker-based robotic projects//'
-    echo -e "${MSG_END_FORMAT}"
+    # Note:
+    #   - Strip shell comment bloc comment character `#` of both empty line and line with text,
+    #   - Delete both horizontal lines
+    #   - Delet both header ligne
+    echo -e "${DOCUMENTATION_BUFFER_DNP}" | sed '/\# ====.*/d' | sed 's/^\# //' | sed 's/^\#//' | sed '/Dockerized-NorLab-Project (DNP)/d' | sed '/A tool for managing Docker-based robotic projects/d' | sed "/Run 'dnp COMMAND --help' for more information on a command./d"
+    echo -e "Run ${MSG_DIMMED_FORMAT}dnp COMMAND --help${MSG_END_FORMAT} for more information on a command."
+    exit 0
 }
 
 function dnp::show_entrypoint_help_no_splash() {
-    echo -e "${MSG_DIMMED_FORMAT}"
-    n2st::draw_horizontal_line_across_the_terminal_window "="
-    echo -e "dnp help"
-    n2st::echo_centering_str "Dockerized-NorLab-Project (DNP)" "${MSG_DIMMED_FORMAT}" " "
-    n2st::echo_centering_str "A tool for managing Docker-based robotic projects" "${MSG_DIMMED_FORMAT}" " "
-    # Strip shell comment char `#` and both lines
-    echo -e "${MSG_DIMMED_FORMAT}${DOCUMENTATION_BUFFER_DNP}" | sed 's/\# ====.*//' | sed 's/^\#//' | sed 's/Dockerized-NorLab-Project (DNP)//' | sed 's/A tool for managing Docker-based robotic projects//'
-    n2st::draw_horizontal_line_across_the_terminal_window "="
-    echo -e "${MSG_END_FORMAT}"
+    # Note:
+    #   - Strip shell comment bloc comment character `#` of both empty line and line with text,
+    #   - Delete both horizontal lines
+    #   - Reformat the header left align
+    echo -e "${DOCUMENTATION_BUFFER_DNP}" | sed '/\# ====.*/d' | sed 's/^\# //' | sed 's/^\#//' | sed 's/^[[:space:]]*Dockerized-NorLab-Project (DNP)/Dockerized-NorLab-Project (DNP)/' | sed 's/^[[:space:]]*A tool for managing Docker-based robotic projects/A tool for managing Docker-based robotic projects/'
+    exit 0
 }
 
 # ::::Main:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
